-- Disattivare safe update mode
SET SQL_SAFE_UPDATES = 0;

SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));

-- VADO A TOGLIERE L'OVERHEAD DEI CODICI ATECO SULLA TABELLA DEI SOGGETTI
UPDATE soggetti_3
SET COD_ATECO_SOGG = REPLACE(COD_ATECO_SOGG, '_2007', '');
update soggetti_3
SET COD_ATECO_SOGG = REPLACE(COD_ATECO_SOGG, '_2', '');


-- Trovo i codici ateco mancanti
SELECT soggetti_3.COD_ATECO_SOGG
FROM soggetti_3
WHERE COD_ATECO_SOGG not in (select ateco.COD_ATECO as ateco
  from soggetti_3 inner join ateco 
  on soggetti_3.COD_ATECO_SOGG=ateco.COD_ATECO
  order by(ateco)) and LENGTH(COD_ATECO_SOGG) > 1;
  
-- A questo punto aggiungo i codici ateco mancanti
INSERT INTO ateco (COD_ATECO, Descrizione) VALUES ('82.20', 'Attività dei call center');
INSERT INTO ateco (COD_ATECO, Descrizione) VALUES ('72.19.00','Altre attività di ricerca e sviluppo sperimentale nel campo delle scienze naturali e dell ingegneria');
INSERT INTO ateco (COD_ATECO, Descrizione) VALUES ('53.10','Attività postali con obbligo di servizio universale');
INSERT INTO ateco (COD_ATECO, Descrizione) VALUES ('26.20','Fabbricazione di computer e unità periferiche');
INSERT INTO ateco (COD_ATECO, Descrizione) VALUES ('63.11.10','Elaborazione dati');
INSERT INTO ateco (COD_ATECO, Descrizione) VALUES ('08.12',' sabbia; estrazione di argille e caolino');

-- A questo punto conto di nuovo quante aziende trovo con la tabella appena importata: [1417]
select distinct count(ateco.COD_ATECO) as ateco
  from soggetti_3 inner join ateco 
  on soggetti_3.COD_ATECO_SOGG=ateco.COD_ATECO
  order by(ateco);
  
-- una volta tolto l'overhead e aggiunte le chiavi mancanti
-- posso fare la inner join con la tabella ateco
-- Descrizione settoriale del codice ateco di ogni azienda
select ateco.COD_ATECO as ateco,
    soggetti_3.OC_DENOMINAZIONE_SOGG as nome_azienda,
    ateco.Descrizione as settore
  from soggetti_3 inner join ateco 
  on soggetti_3.COD_ATECO_SOGG=ateco.COD_ATECO
  order by(ateco);
  
  -- CLOUD COMPUTING
  select *
from PROGETTI_3
where OC_TITOLO_PROGETTO like '%cloud%'
   or OC_TITOLO_PROGETTO like '%computing%'
   or OC_SINTESI_PROGETTO like '%cloud%'
   or OC_SINTESI_PROGETTO like '%computing%'
   or CUP_DESCR_NATURA like '%cloud%'
   or CUP_DESCR_NATURA like '%computing%'
   or CUP_DESCR_TIPOLOGIA like '%cloud%'
   or CUP_DESCR_TIPOLOGIA like '%computing%'
   or CUP_DESCR_SETTORE like '%cloud%'
   or CUP_DESCR_SETTORE like '%computing%'
   or CUP_DESCR_SOTTOSETTORE like '%cloud%'
   or CUP_DESCR_SOTTOSETTORE like '%computing%'
   or CUP_DESCR_CATEGORIA like '%cloud%'
   or CUP_DESCR_CATEGORIA like '%computing%';

-- BIG DATA
select *
from PROGETTI_ALL
where OC_TITOLO_PROGETTO like '%big data%'
   or OC_SINTESI_PROGETTO like '%big data%'
   or CUP_DESCR_NATURA like '%big data%'
   or CUP_DESCR_TIPOLOGIA like '%big data%'
   or CUP_DESCR_SETTORE like '%big data%'
   or CUP_DESCR_SOTTOSETTORE like '%big data%'
   or CUP_DESCR_CATEGORIA like '%big data%'
   or OC_TITOLO_PROGETTO like '%analytics%'
   or OC_SINTESI_PROGETTO like '%analytics%'
   or CUP_DESCR_NATURA like '%analytics%'
   or CUP_DESCR_TIPOLOGIA like '%analytics%'
   or CUP_DESCR_SETTORE like '%analytics%'
   or CUP_DESCR_SOTTOSETTORE like '%analytics%'
   or CUP_DESCR_CATEGORIA like '%analytics%'
   or OC_TITOLO_PROGETTO like '%analisi dei dati%'
   or OC_SINTESI_PROGETTO like '%analisi dei dati%'
   or CUP_DESCR_NATURA like '%analisi dei dati%'
   or CUP_DESCR_TIPOLOGIA like '%analisi dei dati%'
   or CUP_DESCR_SETTORE like '%analisi dei dati%'
   or CUP_DESCR_SOTTOSETTORE like '%analisi dei dati%'
   or CUP_DESCR_CATEGORIA like '%analisi dei dati%'
   or OC_TITOLO_PROGETTO like '%data mining%'
   or OC_SINTESI_PROGETTO like '%data mining%'
   or CUP_DESCR_NATURA like '%data mining%'
   or CUP_DESCR_TIPOLOGIA like '%data mining%'
   or CUP_DESCR_SETTORE like '%data mining%'
   or CUP_DESCR_SOTTOSETTORE like '%data mining%'
   or CUP_DESCR_CATEGORIA like '%data mining%'
   or OC_TITOLO_PROGETTO like '%machine learning%'
   or OC_SINTESI_PROGETTO like '%machine learning%'
   or CUP_DESCR_NATURA like '%machine learning%'
   or CUP_DESCR_TIPOLOGIA like '%machine learning%'
   or CUP_DESCR_SETTORE like '%machine learning%'
   or CUP_DESCR_SOTTOSETTORE like '%machine learning%'
   or CUP_DESCR_CATEGORIA like '%machine learning%';


-- CYBER SECURITY
  select *
from PROGETTI_ALL
where OC_TITOLO_PROGETTO like '%cyber security%'
   or OC_SINTESI_PROGETTO like '%cyber security%'
   or CUP_DESCR_NATURA like '%cyber security%'
   or CUP_DESCR_TIPOLOGIA like '%cyber security%'
   or CUP_DESCR_SETTORE like '%cyber security%'
   or CUP_DESCR_SOTTOSETTORE like '%cyber security%'
   or CUP_DESCR_CATEGORIA like '%cyber security%'
   or OC_TITOLO_PROGETTO like '%cybersecurity%'
   or OC_SINTESI_PROGETTO like '%cybersecurity%'
   or CUP_DESCR_NATURA like '%cybersecurity%'
   or CUP_DESCR_TIPOLOGIA like '%cybersecurity%'
   or CUP_DESCR_SETTORE like '%cybersecurity%'
   or CUP_DESCR_SOTTOSETTORE like '%cybersecurity%'
   or CUP_DESCR_CATEGORIA like '%cybersecurity%'
   or OC_TITOLO_PROGETTO like '%gdpr%'
   or OC_SINTESI_PROGETTO like '%gdpr%'
   or CUP_DESCR_NATURA like '%gdpr%'
   or CUP_DESCR_TIPOLOGIA like '%gdpr%'
   or CUP_DESCR_SETTORE like '%gdpr%'
   or CUP_DESCR_SOTTOSETTORE like '%gdpr%'
   or CUP_DESCR_CATEGORIA like '%gdpr%'
   or OC_TITOLO_PROGETTO like '%blockchain%'
   or OC_SINTESI_PROGETTO like '%blockchain%'
   or CUP_DESCR_NATURA like '%blockchain%'
   or CUP_DESCR_TIPOLOGIA like '%blockchain%'
   or CUP_DESCR_SETTORE like '%blockchain%'
   or CUP_DESCR_SOTTOSETTORE like '%blockchain%'
   or CUP_DESCR_CATEGORIA like '%blockchain%'
   or OC_TITOLO_PROGETTO like '%sicurezza informatica%'
   or OC_SINTESI_PROGETTO like '%sicurezza informatica%'
   or CUP_DESCR_NATURA like '%sicurezza informatica%'
   or CUP_DESCR_TIPOLOGIA like '%sicurezza informatica%'
   or CUP_DESCR_SETTORE like '%sicurezza informatica%'
   or CUP_DESCR_SOTTOSETTORE like '%sicurezza informatica%'
   or CUP_DESCR_CATEGORIA like '%sicurezza informatica%'
   or OC_TITOLO_PROGETTO like '%malware%'
   or OC_SINTESI_PROGETTO like '%malware%'
   or CUP_DESCR_NATURA like '%malware%'
   or CUP_DESCR_TIPOLOGIA like '%malware%'
   or CUP_DESCR_SETTORE like '%malware%'
   or CUP_DESCR_SOTTOSETTORE like '%malware%'
   or CUP_DESCR_CATEGORIA like '%malware%'
   or OC_TITOLO_PROGETTO like '%antivirus%'
   or OC_SINTESI_PROGETTO like '%antivirus%'
   or CUP_DESCR_NATURA like '%antivirus%'
   or CUP_DESCR_TIPOLOGIA like '%antivirus%'
   or CUP_DESCR_SETTORE like '%antivirus%'
   or CUP_DESCR_SOTTOSETTORE like '%antivirus%'
   or CUP_DESCR_CATEGORIA like '%antivirus%'
   or OC_TITOLO_PROGETTO like '%crittografia%'
   or OC_SINTESI_PROGETTO like '%crittografia%'
   or CUP_DESCR_NATURA like '%crittografia%'
   or CUP_DESCR_TIPOLOGIA like '%crittografia%'
   or CUP_DESCR_SETTORE like '%crittografia%'
   or CUP_DESCR_SOTTOSETTORE like '%crittografia%'
   or CUP_DESCR_CATEGORIA like '%crittografia%'
   or OC_TITOLO_PROGETTO like '%firma digitale%'
   or OC_SINTESI_PROGETTO like '%firma digitale%'
   or CUP_DESCR_NATURA like '%firma digitale%'
   or CUP_DESCR_TIPOLOGIA like '%firma digitale%'
   or CUP_DESCR_SETTORE like '%firma digitale%'
   or CUP_DESCR_SOTTOSETTORE like '%firma digitale%'
   or CUP_DESCR_CATEGORIA like '%firma digitale%'
   or OC_TITOLO_PROGETTO like '%firewall%'
   or OC_SINTESI_PROGETTO like '%firewall%'
   or CUP_DESCR_NATURA like '%firfirewall%'
   or CUP_DESCR_SETTORE like '%firewall%'
   or CUP_DESCR_SOTTOSETTORE like '%firewall%'
   or CUP_DESCR_CATEGORIA like '%firewall%'
   or OC_TITOLO_PROGETTO like '%privacy%'
   or OC_SINTESI_PROGETTO like '%privacy%'
   or CUP_DESCR_NATURA like '%privacy%'
   or CUP_DESCR_SETTORE like '%privacy%'
   or CUP_DESCR_SOTTOSETTORE like '%privacy%'
   or CUP_DESCR_CATEGORIA like '%privacy%'
   or OC_TITOLO_PROGETTO like '%autenticazione%'
   or OC_SINTESI_PROGETTO like '%autenticazione%'
   or CUP_DESCR_NATURA like '%autenticazione%'
   or CUP_DESCR_SETTORE like '%autenticazione%'
   or CUP_DESCR_SOTTOSETTORE like '%autenticazione%'
   or CUP_DESCR_CATEGORIA like '%autenticazione%'
   or OC_TITOLO_PROGETTO like '%VPN%'
   or OC_SINTESI_PROGETTO like '%VPN%'
   or CUP_DESCR_NATURA like '%VPN%'
   or CUP_DESCR_SETTORE like '%VPN%'
   or CUP_DESCR_SOTTOSETTORE like '%VPN%'
   or CUP_DESCR_CATEGORIA like '%VPN%';


-- TOP SETTORI DI IMPIEGO [PIE CHARTS]

-- CLASSIFICA GLOBALE
select ateco.COD_ATECO as ateco,
    max(ateco.Descrizione) as descrizione,
    count(ateco.COD_ATECO) as cardinalita
  from soggetti_3 inner join ateco 
  on soggetti_3.COD_ATECO_SOGG=ateco.COD_ATECO
  inner join progetti_3 on progetti_3.COD_LOCALE_PROGETTO = soggetti_3.COD_LOCALE_PROGETTO
  where OC_TITOLO_PROGETTO like '%cloud%'
   or OC_TITOLO_PROGETTO like '%computing%'
   or OC_SINTESI_PROGETTO like '%cloud%'
   or OC_SINTESI_PROGETTO like '%computing%'
   or CUP_DESCR_NATURA like '%cloud%'
   or CUP_DESCR_NATURA like '%computing%'
   or CUP_DESCR_TIPOLOGIA like '%cloud%'
   or CUP_DESCR_TIPOLOGIA like '%computing%'
   or CUP_DESCR_SETTORE like '%cloud%'
   or CUP_DESCR_SETTORE like '%computing%'
   or CUP_DESCR_SOTTOSETTORE like '%cloud%'
   or CUP_DESCR_SOTTOSETTORE like '%computing%'
   or CUP_DESCR_CATEGORIA like '%cloud%'
   or CUP_DESCR_CATEGORIA like '%computing%'
   --cyber security
   or OC_TITOLO_PROGETTO like '%cyber security%'
   or OC_SINTESI_PROGETTO like '%cyber security%'
   or CUP_DESCR_NATURA like '%cyber security%'
   or CUP_DESCR_TIPOLOGIA like '%cyber security%'
   or CUP_DESCR_SETTORE like '%cyber security%'
   or CUP_DESCR_SOTTOSETTORE like '%cyber security%'
   or CUP_DESCR_CATEGORIA like '%cyber security%'
   or OC_TITOLO_PROGETTO like '%cybersecurity%'
   or OC_SINTESI_PROGETTO like '%cybersecurity%'
   or CUP_DESCR_NATURA like '%cybersecurity%'
   or CUP_DESCR_TIPOLOGIA like '%cybersecurity%'
   or CUP_DESCR_SETTORE like '%cybersecurity%'
   or CUP_DESCR_SOTTOSETTORE like '%cybersecurity%'
   or CUP_DESCR_CATEGORIA like '%cybersecurity%'
   or OC_TITOLO_PROGETTO like '%gdpr%'
   or OC_SINTESI_PROGETTO like '%gdpr%'
   or CUP_DESCR_NATURA like '%gdpr%'
   or CUP_DESCR_TIPOLOGIA like '%gdpr%'
   or CUP_DESCR_SETTORE like '%gdpr%'
   or CUP_DESCR_SOTTOSETTORE like '%gdpr%'
   or CUP_DESCR_CATEGORIA like '%gdpr%'
   or OC_TITOLO_PROGETTO like '%blockchain%'
   or OC_SINTESI_PROGETTO like '%blockchain%'
   or CUP_DESCR_NATURA like '%blockchain%'
   or CUP_DESCR_TIPOLOGIA like '%blockchain%'
   or CUP_DESCR_SETTORE like '%blockchain%'
   or CUP_DESCR_SOTTOSETTORE like '%blockchain%'
   or CUP_DESCR_CATEGORIA like '%blockchain%'
   or OC_TITOLO_PROGETTO like '%sicurezza informatica%'
   or OC_SINTESI_PROGETTO like '%sicurezza informatica%'
   or CUP_DESCR_NATURA like '%sicurezza informatica%'
   or CUP_DESCR_TIPOLOGIA like '%sicurezza informatica%'
   or CUP_DESCR_SETTORE like '%sicurezza informatica%'
   or CUP_DESCR_SOTTOSETTORE like '%sicurezza informatica%'
   or CUP_DESCR_CATEGORIA like '%sicurezza informatica%'
   or OC_TITOLO_PROGETTO like '%malware%'
   or OC_SINTESI_PROGETTO like '%malware%'
   or CUP_DESCR_NATURA like '%malware%'
   or CUP_DESCR_TIPOLOGIA like '%malware%'
   or CUP_DESCR_SETTORE like '%malware%'
   or CUP_DESCR_SOTTOSETTORE like '%malware%'
   or CUP_DESCR_CATEGORIA like '%malware%'
   or OC_TITOLO_PROGETTO like '%antivirus%'
   or OC_SINTESI_PROGETTO like '%antivirus%'
   or CUP_DESCR_NATURA like '%antivirus%'
   or CUP_DESCR_TIPOLOGIA like '%antivirus%'
   or CUP_DESCR_SETTORE like '%antivirus%'
   or CUP_DESCR_SOTTOSETTORE like '%antivirus%'
   or CUP_DESCR_CATEGORIA like '%antivirus%'
   or OC_TITOLO_PROGETTO like '%crittografia%'
   or OC_SINTESI_PROGETTO like '%crittografia%'
   or CUP_DESCR_NATURA like '%crittografia%'
   or CUP_DESCR_TIPOLOGIA like '%crittografia%'
   or CUP_DESCR_SETTORE like '%crittografia%'
   or CUP_DESCR_SOTTOSETTORE like '%crittografia%'
   or CUP_DESCR_CATEGORIA like '%crittografia%'
   or OC_TITOLO_PROGETTO like '%firma digitale%'
   or OC_SINTESI_PROGETTO like '%firma digitale%'
   or CUP_DESCR_NATURA like '%firma digitale%'
   or CUP_DESCR_TIPOLOGIA like '%firma digitale%'
   or CUP_DESCR_SETTORE like '%firma digitale%'
   or CUP_DESCR_SOTTOSETTORE like '%firma digitale%'
   or CUP_DESCR_CATEGORIA like '%firma digitale%'
   or OC_TITOLO_PROGETTO like '%firewall%'
   or OC_SINTESI_PROGETTO like '%firewall%'
   or CUP_DESCR_NATURA like '%firfirewall%'
   or CUP_DESCR_SETTORE like '%firewall%'
   or CUP_DESCR_SOTTOSETTORE like '%firewall%'
   or CUP_DESCR_CATEGORIA like '%firewall%'
   or OC_TITOLO_PROGETTO like '%privacy%'
   or OC_SINTESI_PROGETTO like '%privacy%'
   or CUP_DESCR_NATURA like '%privacy%'
   or CUP_DESCR_SETTORE like '%privacy%'
   or CUP_DESCR_SOTTOSETTORE like '%privacy%'
   or CUP_DESCR_CATEGORIA like '%privacy%'
   or OC_TITOLO_PROGETTO like '%autenticazione%'
   or OC_SINTESI_PROGETTO like '%autenticazione%'
   or CUP_DESCR_NATURA like '%autenticazione%'
   or CUP_DESCR_SETTORE like '%autenticazione%'
   or CUP_DESCR_SOTTOSETTORE like '%autenticazione%'
   or CUP_DESCR_CATEGORIA like '%autenticazione%'
   or OC_TITOLO_PROGETTO like '%VPN%'
   or OC_SINTESI_PROGETTO like '%VPN%'
   or CUP_DESCR_NATURA like '%VPN%'
   or CUP_DESCR_SETTORE like '%VPN%'
   or CUP_DESCR_SOTTOSETTORE like '%VPN%'
   or CUP_DESCR_CATEGORIA like '%VPN%';
   --big data
   or OC_TITOLO_PROGETTO like '%big data%'
   or OC_SINTESI_PROGETTO like '%big data%'
   or CUP_DESCR_NATURA like '%big data%'
   or CUP_DESCR_TIPOLOGIA like '%big data%'
   or CUP_DESCR_SETTORE like '%big data%'
   or CUP_DESCR_SOTTOSETTORE like '%big data%'
   or CUP_DESCR_CATEGORIA like '%big data%'
   or OC_TITOLO_PROGETTO like '%analytics%'
   or OC_SINTESI_PROGETTO like '%analytics%'
   or CUP_DESCR_NATURA like '%analytics%'
   or CUP_DESCR_TIPOLOGIA like '%analytics%'
   or CUP_DESCR_SETTORE like '%analytics%'
   or CUP_DESCR_SOTTOSETTORE like '%analytics%'
   or CUP_DESCR_CATEGORIA like '%analytics%'
   or OC_TITOLO_PROGETTO like '%analisi dei dati%'
   or OC_SINTESI_PROGETTO like '%analisi dei dati%'
   or CUP_DESCR_NATURA like '%analisi dei dati%'
   or CUP_DESCR_TIPOLOGIA like '%analisi dei dati%'
   or CUP_DESCR_SETTORE like '%analisi dei dati%'
   or CUP_DESCR_SOTTOSETTORE like '%analisi dei dati%'
   or CUP_DESCR_CATEGORIA like '%analisi dei dati%'
   or OC_TITOLO_PROGETTO like '%data mining%'
   or OC_SINTESI_PROGETTO like '%data mining%'
   or CUP_DESCR_NATURA like '%data mining%'
   or CUP_DESCR_TIPOLOGIA like '%data mining%'
   or CUP_DESCR_SETTORE like '%data mining%'
   or CUP_DESCR_SOTTOSETTORE like '%data mining%'
   or CUP_DESCR_CATEGORIA like '%data mining%'
   or OC_TITOLO_PROGETTO like '%machine learning%'
   or OC_SINTESI_PROGETTO like '%machine learning%'
   or CUP_DESCR_NATURA like '%machine learning%'
   or CUP_DESCR_TIPOLOGIA like '%machine learning%'
   or CUP_DESCR_SETTORE like '%machine learning%'
   or CUP_DESCR_SOTTOSETTORE like '%machine learning%'
   or CUP_DESCR_CATEGORIA like '%machine learning%';
   group by (ateco)
   order by(cardinalita) desc;


-- CLOUD COMPUTING [PIE CHART]
select ateco.COD_ATECO as ateco,
    max(ateco.Descrizione) as descrizione,
       count(ateco.COD_ATECO) as cardinalita
  from soggetti_3 inner join ateco 
  on soggetti_3.COD_ATECO_SOGG=ateco.COD_ATECO
  inner join progetti_3 on progetti_3.COD_LOCALE_PROGETTO = soggetti_3.COD_LOCALE_PROGETTO
  where OC_TITOLO_PROGETTO like '%cloud%'
   or OC_TITOLO_PROGETTO like '%computing%'
   or OC_SINTESI_PROGETTO like '%cloud%'
   or OC_SINTESI_PROGETTO like '%computing%'
   or CUP_DESCR_NATURA like '%cloud%'
   or CUP_DESCR_NATURA like '%computing%'
   or CUP_DESCR_TIPOLOGIA like '%cloud%'
   or CUP_DESCR_TIPOLOGIA like '%computing%'
   or CUP_DESCR_SETTORE like '%cloud%'
   or CUP_DESCR_SETTORE like '%computing%'
   or CUP_DESCR_SOTTOSETTORE like '%cloud%'
   or CUP_DESCR_SOTTOSETTORE like '%computing%'
   or CUP_DESCR_CATEGORIA like '%cloud%'
   or CUP_DESCR_CATEGORIA like '%computing%'
   group by (ateco)
   order by(cardinalita) desc;

-- BIG DATA [PIE CHART]
select ateco.COD_ATECO as ateco,
    max(ateco.Descrizione) as descrizione,
       count(ateco.COD_ATECO) as cardinalita
  from soggetti_3 inner join ateco 
  on soggetti_3.COD_ATECO_SOGG=ateco.COD_ATECO
  inner join progetti_3 on progetti_3.COD_LOCALE_PROGETTO = soggetti_3.COD_LOCALE_PROGETTO
  where OC_TITOLO_PROGETTO like '%big data%'
   or OC_SINTESI_PROGETTO like '%big data%'
   or CUP_DESCR_NATURA like '%big data%'
   or CUP_DESCR_TIPOLOGIA like '%big data%'
   or CUP_DESCR_SETTORE like '%big data%'
   or CUP_DESCR_SOTTOSETTORE like '%big data%'
   or CUP_DESCR_CATEGORIA like '%big data%'
   or OC_TITOLO_PROGETTO like '%analytics%'
   or OC_SINTESI_PROGETTO like '%analytics%'
   or CUP_DESCR_NATURA like '%analytics%'
   or CUP_DESCR_TIPOLOGIA like '%analytics%'
   or CUP_DESCR_SETTORE like '%analytics%'
   or CUP_DESCR_SOTTOSETTORE like '%analytics%'
   or CUP_DESCR_CATEGORIA like '%analytics%'
   or OC_TITOLO_PROGETTO like '%analisi dei dati%'
   or OC_SINTESI_PROGETTO like '%analisi dei dati%'
   or CUP_DESCR_NATURA like '%analisi dei dati%'
   or CUP_DESCR_TIPOLOGIA like '%analisi dei dati%'
   or CUP_DESCR_SETTORE like '%analisi dei dati%'
   or CUP_DESCR_SOTTOSETTORE like '%analisi dei dati%'
   or CUP_DESCR_CATEGORIA like '%analisi dei dati%'
   or OC_TITOLO_PROGETTO like '%data mining%'
   or OC_SINTESI_PROGETTO like '%data mining%'
   or CUP_DESCR_NATURA like '%data mining%'
   or CUP_DESCR_TIPOLOGIA like '%data mining%'
   or CUP_DESCR_SETTORE like '%data mining%'
   or CUP_DESCR_SOTTOSETTORE like '%data mining%'
   or CUP_DESCR_CATEGORIA like '%data mining%'
   or OC_TITOLO_PROGETTO like '%machine learning%'
   or OC_SINTESI_PROGETTO like '%machine learning%'
   or CUP_DESCR_NATURA like '%machine learning%'
   or CUP_DESCR_TIPOLOGIA like '%machine learning%'
   or CUP_DESCR_SETTORE like '%machine learning%'
   or CUP_DESCR_SOTTOSETTORE like '%machine learning%'
   or CUP_DESCR_CATEGORIA like '%machine learning%'
   group by (ateco)
   order by(cardinalita) desc;

-- CYBER SECURITY [PIE CHART]
select ateco.COD_ATECO as ateco,
    max(ateco.Descrizione) as descrizione,
       count(ateco.COD_ATECO) as cardinalita
  from soggetti_3 inner join ateco 
  on soggetti_3.COD_ATECO_SOGG=ateco.COD_ATECO
  inner join progetti_3 on progetti_3.COD_LOCALE_PROGETTO = soggetti_3.COD_LOCALE_PROGETTO
  where OC_TITOLO_PROGETTO like '%cyber security%'
   or OC_SINTESI_PROGETTO like '%cyber security%'
   or CUP_DESCR_NATURA like '%cyber security%'
   or CUP_DESCR_TIPOLOGIA like '%cyber security%'
   or CUP_DESCR_SETTORE like '%cyber security%'
   or CUP_DESCR_SOTTOSETTORE like '%cyber security%'
   or CUP_DESCR_CATEGORIA like '%cyber security%'
   or OC_TITOLO_PROGETTO like '%cybersecurity%'
   or OC_SINTESI_PROGETTO like '%cybersecurity%'
   or CUP_DESCR_NATURA like '%cybersecurity%'
   or CUP_DESCR_TIPOLOGIA like '%cybersecurity%'
   or CUP_DESCR_SETTORE like '%cybersecurity%'
   or CUP_DESCR_SOTTOSETTORE like '%cybersecurity%'
   or CUP_DESCR_CATEGORIA like '%cybersecurity%'
   or OC_TITOLO_PROGETTO like '%gdpr%'
   or OC_SINTESI_PROGETTO like '%gdpr%'
   or CUP_DESCR_NATURA like '%gdpr%'
   or CUP_DESCR_TIPOLOGIA like '%gdpr%'
   or CUP_DESCR_SETTORE like '%gdpr%'
   or CUP_DESCR_SOTTOSETTORE like '%gdpr%'
   or CUP_DESCR_CATEGORIA like '%gdpr%'
   or OC_TITOLO_PROGETTO like '%blockchain%'
   or OC_SINTESI_PROGETTO like '%blockchain%'
   or CUP_DESCR_NATURA like '%blockchain%'
   or CUP_DESCR_TIPOLOGIA like '%blockchain%'
   or CUP_DESCR_SETTORE like '%blockchain%'
   or CUP_DESCR_SOTTOSETTORE like '%blockchain%'
   or CUP_DESCR_CATEGORIA like '%blockchain%'
   or OC_TITOLO_PROGETTO like '%sicurezza informatica%'
   or OC_SINTESI_PROGETTO like '%sicurezza informatica%'
   or CUP_DESCR_NATURA like '%sicurezza informatica%'
   or CUP_DESCR_TIPOLOGIA like '%sicurezza informatica%'
   or CUP_DESCR_SETTORE like '%sicurezza informatica%'
   or CUP_DESCR_SOTTOSETTORE like '%sicurezza informatica%'
   or CUP_DESCR_CATEGORIA like '%sicurezza informatica%'
   or OC_TITOLO_PROGETTO like '%malware%'
   or OC_SINTESI_PROGETTO like '%malware%'
   or CUP_DESCR_NATURA like '%malware%'
   or CUP_DESCR_TIPOLOGIA like '%malware%'
   or CUP_DESCR_SETTORE like '%malware%'
   or CUP_DESCR_SOTTOSETTORE like '%malware%'
   or CUP_DESCR_CATEGORIA like '%malware%'
   or OC_TITOLO_PROGETTO like '%antivirus%'
   or OC_SINTESI_PROGETTO like '%antivirus%'
   or CUP_DESCR_NATURA like '%antivirus%'
   or CUP_DESCR_TIPOLOGIA like '%antivirus%'
   or CUP_DESCR_SETTORE like '%antivirus%'
   or CUP_DESCR_SOTTOSETTORE like '%antivirus%'
   or CUP_DESCR_CATEGORIA like '%antivirus%'
   or OC_TITOLO_PROGETTO like '%crittografia%'
   or OC_SINTESI_PROGETTO like '%crittografia%'
   or CUP_DESCR_NATURA like '%crittografia%'
   or CUP_DESCR_TIPOLOGIA like '%crittografia%'
   or CUP_DESCR_SETTORE like '%crittografia%'
   or CUP_DESCR_SOTTOSETTORE like '%crittografia%'
   or CUP_DESCR_CATEGORIA like '%crittografia%'
   or OC_TITOLO_PROGETTO like '%firma digitale%'
   or OC_SINTESI_PROGETTO like '%firma digitale%'
   or CUP_DESCR_NATURA like '%firma digitale%'
   or CUP_DESCR_TIPOLOGIA like '%firma digitale%'
   or CUP_DESCR_SETTORE like '%firma digitale%'
   or CUP_DESCR_SOTTOSETTORE like '%firma digitale%'
   or CUP_DESCR_CATEGORIA like '%firma digitale%'
   or OC_TITOLO_PROGETTO like '%firewall%'
   or OC_SINTESI_PROGETTO like '%firewall%'
   or CUP_DESCR_NATURA like '%firfirewall%'
   or CUP_DESCR_SETTORE like '%firewall%'
   or CUP_DESCR_SOTTOSETTORE like '%firewall%'
   or CUP_DESCR_CATEGORIA like '%firewall%'
   or OC_TITOLO_PROGETTO like '%privacy%'
   or OC_SINTESI_PROGETTO like '%privacy%'
   or CUP_DESCR_NATURA like '%privacy%'
   or CUP_DESCR_SETTORE like '%privacy%'
   or CUP_DESCR_SOTTOSETTORE like '%privacy%'
   or CUP_DESCR_CATEGORIA like '%privacy%'
   or OC_TITOLO_PROGETTO like '%autenticazione%'
   or OC_SINTESI_PROGETTO like '%autenticazione%'
   or CUP_DESCR_NATURA like '%autenticazione%'
   or CUP_DESCR_SETTORE like '%autenticazione%'
   or CUP_DESCR_SOTTOSETTORE like '%autenticazione%'
   or CUP_DESCR_CATEGORIA like '%autenticazione%'
   or OC_TITOLO_PROGETTO like '%VPN%'
   or OC_SINTESI_PROGETTO like '%VPN%'
   or CUP_DESCR_NATURA like '%VPN%'
   or CUP_DESCR_SETTORE like '%VPN%'
   or CUP_DESCR_SOTTOSETTORE like '%VPN%'
   or CUP_DESCR_CATEGORIA like '%VPN%'
   group by (ateco)
   order by(cardinalita) desc;


-- RICERCA PER DATA DI INIZIO : RUN CHARTS

-- GLOBALE [RUN CHART]
select ateco.COD_ATECO as ateco,
    max(ateco.Descrizione) as descrizione,
       count(ateco.COD_ATECO) as cardinalita
  from soggetti_3 inner join ateco 
  on soggetti_3.COD_ATECO_SOGG=ateco.COD_ATECO
  inner join progetti_3 on progetti_3.COD_LOCALE_PROGETTO = soggetti_3.COD_LOCALE_PROGETTO
  where (OC_TITOLO_PROGETTO like '%cloud%'
   or OC_TITOLO_PROGETTO like '%computing%'
   or OC_SINTESI_PROGETTO like '%cloud%'
   or OC_SINTESI_PROGETTO like '%computing%'
   or CUP_DESCR_NATURA like '%cloud%'
   or CUP_DESCR_NATURA like '%computing%'
   or CUP_DESCR_TIPOLOGIA like '%cloud%'
   or CUP_DESCR_TIPOLOGIA like '%computing%'
   or CUP_DESCR_SETTORE like '%cloud%'
   or CUP_DESCR_SETTORE like '%computing%'
   or CUP_DESCR_SOTTOSETTORE like '%cloud%'
   or CUP_DESCR_SOTTOSETTORE like '%computing%'
   or CUP_DESCR_CATEGORIA like '%cloud%'
   or CUP_DESCR_CATEGORIA like '%computing%'
   --cyber security
   or OC_TITOLO_PROGETTO like '%cyber security%'
   or OC_SINTESI_PROGETTO like '%cyber security%'
   or CUP_DESCR_NATURA like '%cyber security%'
   or CUP_DESCR_TIPOLOGIA like '%cyber security%'
   or CUP_DESCR_SETTORE like '%cyber security%'
   or CUP_DESCR_SOTTOSETTORE like '%cyber security%'
   or CUP_DESCR_CATEGORIA like '%cyber security%'
   or OC_TITOLO_PROGETTO like '%cybersecurity%'
   or OC_SINTESI_PROGETTO like '%cybersecurity%'
   or CUP_DESCR_NATURA like '%cybersecurity%'
   or CUP_DESCR_TIPOLOGIA like '%cybersecurity%'
   or CUP_DESCR_SETTORE like '%cybersecurity%'
   or CUP_DESCR_SOTTOSETTORE like '%cybersecurity%'
   or CUP_DESCR_CATEGORIA like '%cybersecurity%'
   or OC_TITOLO_PROGETTO like '%gdpr%'
   or OC_SINTESI_PROGETTO like '%gdpr%'
   or CUP_DESCR_NATURA like '%gdpr%'
   or CUP_DESCR_TIPOLOGIA like '%gdpr%'
   or CUP_DESCR_SETTORE like '%gdpr%'
   or CUP_DESCR_SOTTOSETTORE like '%gdpr%'
   or CUP_DESCR_CATEGORIA like '%gdpr%'
   or OC_TITOLO_PROGETTO like '%blockchain%'
   or OC_SINTESI_PROGETTO like '%blockchain%'
   or CUP_DESCR_NATURA like '%blockchain%'
   or CUP_DESCR_TIPOLOGIA like '%blockchain%'
   or CUP_DESCR_SETTORE like '%blockchain%'
   or CUP_DESCR_SOTTOSETTORE like '%blockchain%'
   or CUP_DESCR_CATEGORIA like '%blockchain%'
   or OC_TITOLO_PROGETTO like '%sicurezza informatica%'
   or OC_SINTESI_PROGETTO like '%sicurezza informatica%'
   or CUP_DESCR_NATURA like '%sicurezza informatica%'
   or CUP_DESCR_TIPOLOGIA like '%sicurezza informatica%'
   or CUP_DESCR_SETTORE like '%sicurezza informatica%'
   or CUP_DESCR_SOTTOSETTORE like '%sicurezza informatica%'
   or CUP_DESCR_CATEGORIA like '%sicurezza informatica%'
   or OC_TITOLO_PROGETTO like '%malware%'
   or OC_SINTESI_PROGETTO like '%malware%'
   or CUP_DESCR_NATURA like '%malware%'
   or CUP_DESCR_TIPOLOGIA like '%malware%'
   or CUP_DESCR_SETTORE like '%malware%'
   or CUP_DESCR_SOTTOSETTORE like '%malware%'
   or CUP_DESCR_CATEGORIA like '%malware%'
   or OC_TITOLO_PROGETTO like '%antivirus%'
   or OC_SINTESI_PROGETTO like '%antivirus%'
   or CUP_DESCR_NATURA like '%antivirus%'
   or CUP_DESCR_TIPOLOGIA like '%antivirus%'
   or CUP_DESCR_SETTORE like '%antivirus%'
   or CUP_DESCR_SOTTOSETTORE like '%antivirus%'
   or CUP_DESCR_CATEGORIA like '%antivirus%'
   or OC_TITOLO_PROGETTO like '%crittografia%'
   or OC_SINTESI_PROGETTO like '%crittografia%'
   or CUP_DESCR_NATURA like '%crittografia%'
   or CUP_DESCR_TIPOLOGIA like '%crittografia%'
   or CUP_DESCR_SETTORE like '%crittografia%'
   or CUP_DESCR_SOTTOSETTORE like '%crittografia%'
   or CUP_DESCR_CATEGORIA like '%crittografia%'
   or OC_TITOLO_PROGETTO like '%firma digitale%'
   or OC_SINTESI_PROGETTO like '%firma digitale%'
   or CUP_DESCR_NATURA like '%firma digitale%'
   or CUP_DESCR_TIPOLOGIA like '%firma digitale%'
   or CUP_DESCR_SETTORE like '%firma digitale%'
   or CUP_DESCR_SOTTOSETTORE like '%firma digitale%'
   or CUP_DESCR_CATEGORIA like '%firma digitale%'
   or OC_TITOLO_PROGETTO like '%firewall%'
   or OC_SINTESI_PROGETTO like '%firewall%'
   or CUP_DESCR_NATURA like '%firfirewall%'
   or CUP_DESCR_SETTORE like '%firewall%'
   or CUP_DESCR_SOTTOSETTORE like '%firewall%'
   or CUP_DESCR_CATEGORIA like '%firewall%'
   or OC_TITOLO_PROGETTO like '%privacy%'
   or OC_SINTESI_PROGETTO like '%privacy%'
   or CUP_DESCR_NATURA like '%privacy%'
   or CUP_DESCR_SETTORE like '%privacy%'
   or CUP_DESCR_SOTTOSETTORE like '%privacy%'
   or CUP_DESCR_CATEGORIA like '%privacy%'
   or OC_TITOLO_PROGETTO like '%autenticazione%'
   or OC_SINTESI_PROGETTO like '%autenticazione%'
   or CUP_DESCR_NATURA like '%autenticazione%'
   or CUP_DESCR_SETTORE like '%autenticazione%'
   or CUP_DESCR_SOTTOSETTORE like '%autenticazione%'
   or CUP_DESCR_CATEGORIA like '%autenticazione%'
   or OC_TITOLO_PROGETTO like '%VPN%'
   or OC_SINTESI_PROGETTO like '%VPN%'
   or CUP_DESCR_NATURA like '%VPN%'
   or CUP_DESCR_SETTORE like '%VPN%'
   or CUP_DESCR_SOTTOSETTORE like '%VPN%'
   or CUP_DESCR_CATEGORIA like '%VPN%';
   --big data
   or OC_TITOLO_PROGETTO like '%big data%'
   or OC_SINTESI_PROGETTO like '%big data%'
   or CUP_DESCR_NATURA like '%big data%'
   or CUP_DESCR_TIPOLOGIA like '%big data%'
   or CUP_DESCR_SETTORE like '%big data%'
   or CUP_DESCR_SOTTOSETTORE like '%big data%'
   or CUP_DESCR_CATEGORIA like '%big data%'
   or OC_TITOLO_PROGETTO like '%analytics%'
   or OC_SINTESI_PROGETTO like '%analytics%'
   or CUP_DESCR_NATURA like '%analytics%'
   or CUP_DESCR_TIPOLOGIA like '%analytics%'
   or CUP_DESCR_SETTORE like '%analytics%'
   or CUP_DESCR_SOTTOSETTORE like '%analytics%'
   or CUP_DESCR_CATEGORIA like '%analytics%'
   or OC_TITOLO_PROGETTO like '%analisi dei dati%'
   or OC_SINTESI_PROGETTO like '%analisi dei dati%'
   or CUP_DESCR_NATURA like '%analisi dei dati%'
   or CUP_DESCR_TIPOLOGIA like '%analisi dei dati%'
   or CUP_DESCR_SETTORE like '%analisi dei dati%'
   or CUP_DESCR_SOTTOSETTORE like '%analisi dei dati%'
   or CUP_DESCR_CATEGORIA like '%analisi dei dati%'
   or OC_TITOLO_PROGETTO like '%data mining%'
   or OC_SINTESI_PROGETTO like '%data mining%'
   or CUP_DESCR_NATURA like '%data mining%'
   or CUP_DESCR_TIPOLOGIA like '%data mining%'
   or CUP_DESCR_SETTORE like '%data mining%'
   or CUP_DESCR_SOTTOSETTORE like '%data mining%'
   or CUP_DESCR_CATEGORIA like '%data mining%'
   or OC_TITOLO_PROGETTO like '%machine learning%'
   or OC_SINTESI_PROGETTO like '%machine learning%'
   or CUP_DESCR_NATURA like '%machine learning%'
   or CUP_DESCR_TIPOLOGIA like '%machine learning%'
   or CUP_DESCR_SETTORE like '%machine learning%'
   or CUP_DESCR_SOTTOSETTORE like '%machine learning%'
   or CUP_DESCR_CATEGORIA like '%machine learning%')
   and substring(progetti_3.OC_DATA_INIZIO_PROGETTO,1,4) = 2014
   group by (ateco)
   order by(cardinalita) desc;

--CLOUD COMPUTING [RUN CHART]
select ateco.COD_ATECO as ateco,
    max(ateco.Descrizione) as descrizione,
       count(ateco.COD_ATECO) as cardinalita
  from soggetti_3 inner join ateco 
  on soggetti_3.COD_ATECO_SOGG=ateco.COD_ATECO
  inner join progetti_3 on progetti_3.COD_LOCALE_PROGETTO = soggetti_3.COD_LOCALE_PROGETTO
  where (OC_TITOLO_PROGETTO like '%cloud%'
   or OC_TITOLO_PROGETTO like '%computing%'
   or OC_SINTESI_PROGETTO like '%cloud%'
   or OC_SINTESI_PROGETTO like '%computing%'
   or CUP_DESCR_NATURA like '%cloud%'
   or CUP_DESCR_NATURA like '%computing%'
   or CUP_DESCR_TIPOLOGIA like '%cloud%'
   or CUP_DESCR_TIPOLOGIA like '%computing%'
   or CUP_DESCR_SETTORE like '%cloud%'
   or CUP_DESCR_SETTORE like '%computing%'
   or CUP_DESCR_SOTTOSETTORE like '%cloud%'
   or CUP_DESCR_SOTTOSETTORE like '%computing%'
   or CUP_DESCR_CATEGORIA like '%cloud%'
   or CUP_DESCR_CATEGORIA like '%computing%')
   and substring(progetti_3.OC_DATA_INIZIO_PROGETTO,1,4) = 2014
  group by (ateco)
  order by(cardinalita) desc;
  
  -- CYBER SECURITY [RUN CHART]
  select ateco.COD_ATECO as ateco,
    max(ateco.Descrizione) as descrizione,
       count(ateco.COD_ATECO) as cardinalita
  from soggetti_3 inner join ateco 
  on soggetti_3.COD_ATECO_SOGG=ateco.COD_ATECO
  inner join progetti_3 on progetti_3.COD_LOCALE_PROGETTO = soggetti_3.COD_LOCALE_PROGETTO
  where (OC_TITOLO_PROGETTO like '%cyber security%'
   or OC_SINTESI_PROGETTO like '%cyber security%'
   or CUP_DESCR_NATURA like '%cyber security%'
   or CUP_DESCR_TIPOLOGIA like '%cyber security%'
   or CUP_DESCR_SETTORE like '%cyber security%'
   or CUP_DESCR_SOTTOSETTORE like '%cyber security%'
   or CUP_DESCR_CATEGORIA like '%cyber security%'
   or OC_TITOLO_PROGETTO like '%cybersecurity%'
   or OC_SINTESI_PROGETTO like '%cybersecurity%'
   or CUP_DESCR_NATURA like '%cybersecurity%'
   or CUP_DESCR_TIPOLOGIA like '%cybersecurity%'
   or CUP_DESCR_SETTORE like '%cybersecurity%'
   or CUP_DESCR_SOTTOSETTORE like '%cybersecurity%'
   or CUP_DESCR_CATEGORIA like '%cybersecurity%'
   or OC_TITOLO_PROGETTO like '%gdpr%'
   or OC_SINTESI_PROGETTO like '%gdpr%'
   or CUP_DESCR_NATURA like '%gdpr%'
   or CUP_DESCR_TIPOLOGIA like '%gdpr%'
   or CUP_DESCR_SETTORE like '%gdpr%'
   or CUP_DESCR_SOTTOSETTORE like '%gdpr%'
   or CUP_DESCR_CATEGORIA like '%gdpr%'
   or OC_TITOLO_PROGETTO like '%blockchain%'
   or OC_SINTESI_PROGETTO like '%blockchain%'
   or CUP_DESCR_NATURA like '%blockchain%'
   or CUP_DESCR_TIPOLOGIA like '%blockchain%'
   or CUP_DESCR_SETTORE like '%blockchain%'
   or CUP_DESCR_SOTTOSETTORE like '%blockchain%'
   or CUP_DESCR_CATEGORIA like '%blockchain%'
   or OC_TITOLO_PROGETTO like '%sicurezza informatica%'
   or OC_SINTESI_PROGETTO like '%sicurezza informatica%'
   or CUP_DESCR_NATURA like '%sicurezza informatica%'
   or CUP_DESCR_TIPOLOGIA like '%sicurezza informatica%'
   or CUP_DESCR_SETTORE like '%sicurezza informatica%'
   or CUP_DESCR_SOTTOSETTORE like '%sicurezza informatica%'
   or CUP_DESCR_CATEGORIA like '%sicurezza informatica%'
   or OC_TITOLO_PROGETTO like '%malware%'
   or OC_SINTESI_PROGETTO like '%malware%'
   or CUP_DESCR_NATURA like '%malware%'
   or CUP_DESCR_TIPOLOGIA like '%malware%'
   or CUP_DESCR_SETTORE like '%malware%'
   or CUP_DESCR_SOTTOSETTORE like '%malware%'
   or CUP_DESCR_CATEGORIA like '%malware%'
   or OC_TITOLO_PROGETTO like '%antivirus%'
   or OC_SINTESI_PROGETTO like '%antivirus%'
   or CUP_DESCR_NATURA like '%antivirus%'
   or CUP_DESCR_TIPOLOGIA like '%antivirus%'
   or CUP_DESCR_SETTORE like '%antivirus%'
   or CUP_DESCR_SOTTOSETTORE like '%antivirus%'
   or CUP_DESCR_CATEGORIA like '%antivirus%'
   or OC_TITOLO_PROGETTO like '%crittografia%'
   or OC_SINTESI_PROGETTO like '%crittografia%'
   or CUP_DESCR_NATURA like '%crittografia%'
   or CUP_DESCR_TIPOLOGIA like '%crittografia%'
   or CUP_DESCR_SETTORE like '%crittografia%'
   or CUP_DESCR_SOTTOSETTORE like '%crittografia%'
   or CUP_DESCR_CATEGORIA like '%crittografia%'
   or OC_TITOLO_PROGETTO like '%firma digitale%'
   or OC_SINTESI_PROGETTO like '%firma digitale%'
   or CUP_DESCR_NATURA like '%firma digitale%'
   or CUP_DESCR_TIPOLOGIA like '%firma digitale%'
   or CUP_DESCR_SETTORE like '%firma digitale%'
   or CUP_DESCR_SOTTOSETTORE like '%firma digitale%'
   or CUP_DESCR_CATEGORIA like '%firma digitale%'
   or OC_TITOLO_PROGETTO like '%firewall%'
   or OC_SINTESI_PROGETTO like '%firewall%'
   or CUP_DESCR_NATURA like '%firfirewall%'
   or CUP_DESCR_SETTORE like '%firewall%'
   or CUP_DESCR_SOTTOSETTORE like '%firewall%'
   or CUP_DESCR_CATEGORIA like '%firewall%'
   or OC_TITOLO_PROGETTO like '%privacy%'
   or OC_SINTESI_PROGETTO like '%privacy%'
   or CUP_DESCR_NATURA like '%privacy%'
   or CUP_DESCR_SETTORE like '%privacy%'
   or CUP_DESCR_SOTTOSETTORE like '%privacy%'
   or CUP_DESCR_CATEGORIA like '%privacy%'
   or OC_TITOLO_PROGETTO like '%autenticazione%'
   or OC_SINTESI_PROGETTO like '%autenticazione%'
   or CUP_DESCR_NATURA like '%autenticazione%'
   or CUP_DESCR_SETTORE like '%autenticazione%'
   or CUP_DESCR_SOTTOSETTORE like '%autenticazione%'
   or CUP_DESCR_CATEGORIA like '%autenticazione%'
   or OC_TITOLO_PROGETTO like '%VPN%'
   or OC_SINTESI_PROGETTO like '%VPN%'
   or CUP_DESCR_NATURA like '%VPN%'
   or CUP_DESCR_SETTORE like '%VPN%'
   or CUP_DESCR_SOTTOSETTORE like '%VPN%'
   or CUP_DESCR_CATEGORIA like '%VPN%')
   and substring(progetti_3.OC_DATA_INIZIO_PROGETTO,1,4) = 2014
  group by (ateco)
  order by(cardinalita) desc;

-- BIG DATA [RUN CHART]
select ateco.COD_ATECO as ateco,
    max(ateco.Descrizione) as descrizione,
       count(ateco.COD_ATECO) as cardinalita
  from soggetti_3 inner join ateco 
  on soggetti_3.COD_ATECO_SOGG=ateco.COD_ATECO
  inner join progetti_3 on progetti_3.COD_LOCALE_PROGETTO = soggetti_3.COD_LOCALE_PROGETTO
  where (OC_TITOLO_PROGETTO like '%big data%'
   or OC_SINTESI_PROGETTO like '%big data%'
   or CUP_DESCR_NATURA like '%big data%'
   or CUP_DESCR_TIPOLOGIA like '%big data%'
   or CUP_DESCR_SETTORE like '%big data%'
   or CUP_DESCR_SOTTOSETTORE like '%big data%'
   or CUP_DESCR_CATEGORIA like '%big data%'
   or OC_TITOLO_PROGETTO like '%analytics%'
   or OC_SINTESI_PROGETTO like '%analytics%'
   or CUP_DESCR_NATURA like '%analytics%'
   or CUP_DESCR_TIPOLOGIA like '%analytics%'
   or CUP_DESCR_SETTORE like '%analytics%'
   or CUP_DESCR_SOTTOSETTORE like '%analytics%'
   or CUP_DESCR_CATEGORIA like '%analytics%'
   or OC_TITOLO_PROGETTO like '%analisi dei dati%'
   or OC_SINTESI_PROGETTO like '%analisi dei dati%'
   or CUP_DESCR_NATURA like '%analisi dei dati%'
   or CUP_DESCR_TIPOLOGIA like '%analisi dei dati%'
   or CUP_DESCR_SETTORE like '%analisi dei dati%'
   or CUP_DESCR_SOTTOSETTORE like '%analisi dei dati%'
   or CUP_DESCR_CATEGORIA like '%analisi dei dati%'
   or OC_TITOLO_PROGETTO like '%data mining%'
   or OC_SINTESI_PROGETTO like '%data mining%'
   or CUP_DESCR_NATURA like '%data mining%'
   or CUP_DESCR_TIPOLOGIA like '%data mining%'
   or CUP_DESCR_SETTORE like '%data mining%'
   or CUP_DESCR_SOTTOSETTORE like '%data mining%'
   or CUP_DESCR_CATEGORIA like '%data mining%'
   or OC_TITOLO_PROGETTO like '%machine learning%'
   or OC_SINTESI_PROGETTO like '%machine learning%'
   or CUP_DESCR_NATURA like '%machine learning%'
   or CUP_DESCR_TIPOLOGIA like '%machine learning%'
   or CUP_DESCR_SETTORE like '%machine learning%'
   or CUP_DESCR_SOTTOSETTORE like '%machine learning%'
   or CUP_DESCR_CATEGORIA like '%machine learning%')
   and substring(progetti_3.OC_DATA_INIZIO_PROGETTO,1,4) = 2014
   group by (ateco)
   order by(cardinalita) desc;


-- TABELLA GLABLE DEI SETTORI [PIE CHARTS]
select *
from PROGETTI_ALL
where 
   --cloud
   OC_TITOLO_PROGETTO like '%cloud%'
   or OC_TITOLO_PROGETTO like '%computing%'
   or OC_SINTESI_PROGETTO like '%cloud%'
   or OC_SINTESI_PROGETTO like '%computing%'
   or CUP_DESCR_NATURA like '%cloud%'
   or CUP_DESCR_NATURA like '%computing%'
   or CUP_DESCR_TIPOLOGIA like '%cloud%'
   or CUP_DESCR_TIPOLOGIA like '%computing%'
   or CUP_DESCR_SETTORE like '%cloud%'
   or CUP_DESCR_SETTORE like '%computing%'
   or CUP_DESCR_SOTTOSETTORE like '%cloud%'
   or CUP_DESCR_SOTTOSETTORE like '%computing%'
   or CUP_DESCR_CATEGORIA like '%cloud%'
   or CUP_DESCR_CATEGORIA like '%computing%'
   --cyber security
   or OC_TITOLO_PROGETTO like '%cyber security%'
   or OC_SINTESI_PROGETTO like '%cyber security%'
   or CUP_DESCR_NATURA like '%cyber security%'
   or CUP_DESCR_TIPOLOGIA like '%cyber security%'
   or CUP_DESCR_SETTORE like '%cyber security%'
   or CUP_DESCR_SOTTOSETTORE like '%cyber security%'
   or CUP_DESCR_CATEGORIA like '%cyber security%'
   or OC_TITOLO_PROGETTO like '%cybersecurity%'
   or OC_SINTESI_PROGETTO like '%cybersecurity%'
   or CUP_DESCR_NATURA like '%cybersecurity%'
   or CUP_DESCR_TIPOLOGIA like '%cybersecurity%'
   or CUP_DESCR_SETTORE like '%cybersecurity%'
   or CUP_DESCR_SOTTOSETTORE like '%cybersecurity%'
   or CUP_DESCR_CATEGORIA like '%cybersecurity%'
   or OC_TITOLO_PROGETTO like '%gdpr%'
   or OC_SINTESI_PROGETTO like '%gdpr%'
   or CUP_DESCR_NATURA like '%gdpr%'
   or CUP_DESCR_TIPOLOGIA like '%gdpr%'
   or CUP_DESCR_SETTORE like '%gdpr%'
   or CUP_DESCR_SOTTOSETTORE like '%gdpr%'
   or CUP_DESCR_CATEGORIA like '%gdpr%'
   or OC_TITOLO_PROGETTO like '%blockchain%'
   or OC_SINTESI_PROGETTO like '%blockchain%'
   or CUP_DESCR_NATURA like '%blockchain%'
   or CUP_DESCR_TIPOLOGIA like '%blockchain%'
   or CUP_DESCR_SETTORE like '%blockchain%'
   or CUP_DESCR_SOTTOSETTORE like '%blockchain%'
   or CUP_DESCR_CATEGORIA like '%blockchain%'
   or OC_TITOLO_PROGETTO like '%sicurezza informatica%'
   or OC_SINTESI_PROGETTO like '%sicurezza informatica%'
   or CUP_DESCR_NATURA like '%sicurezza informatica%'
   or CUP_DESCR_TIPOLOGIA like '%sicurezza informatica%'
   or CUP_DESCR_SETTORE like '%sicurezza informatica%'
   or CUP_DESCR_SOTTOSETTORE like '%sicurezza informatica%'
   or CUP_DESCR_CATEGORIA like '%sicurezza informatica%'
   or OC_TITOLO_PROGETTO like '%malware%'
   or OC_SINTESI_PROGETTO like '%malware%'
   or CUP_DESCR_NATURA like '%malware%'
   or CUP_DESCR_TIPOLOGIA like '%malware%'
   or CUP_DESCR_SETTORE like '%malware%'
   or CUP_DESCR_SOTTOSETTORE like '%malware%'
   or CUP_DESCR_CATEGORIA like '%malware%'
   or OC_TITOLO_PROGETTO like '%antivirus%'
   or OC_SINTESI_PROGETTO like '%antivirus%'
   or CUP_DESCR_NATURA like '%antivirus%'
   or CUP_DESCR_TIPOLOGIA like '%antivirus%'
   or CUP_DESCR_SETTORE like '%antivirus%'
   or CUP_DESCR_SOTTOSETTORE like '%antivirus%'
   or CUP_DESCR_CATEGORIA like '%antivirus%'
   or OC_TITOLO_PROGETTO like '%crittografia%'
   or OC_SINTESI_PROGETTO like '%crittografia%'
   or CUP_DESCR_NATURA like '%crittografia%'
   or CUP_DESCR_TIPOLOGIA like '%crittografia%'
   or CUP_DESCR_SETTORE like '%crittografia%'
   or CUP_DESCR_SOTTOSETTORE like '%crittografia%'
   or CUP_DESCR_CATEGORIA like '%crittografia%'
   or OC_TITOLO_PROGETTO like '%firma digitale%'
   or OC_SINTESI_PROGETTO like '%firma digitale%'
   or CUP_DESCR_NATURA like '%firma digitale%'
   or CUP_DESCR_TIPOLOGIA like '%firma digitale%'
   or CUP_DESCR_SETTORE like '%firma digitale%'
   or CUP_DESCR_SOTTOSETTORE like '%firma digitale%'
   or CUP_DESCR_CATEGORIA like '%firma digitale%'
   or OC_TITOLO_PROGETTO like '%firewall%'
   or OC_SINTESI_PROGETTO like '%firewall%'
   or CUP_DESCR_NATURA like '%firfirewall%'
   or CUP_DESCR_SETTORE like '%firewall%'
   or CUP_DESCR_SOTTOSETTORE like '%firewall%'
   or CUP_DESCR_CATEGORIA like '%firewall%'
   or OC_TITOLO_PROGETTO like '%privacy%'
   or OC_SINTESI_PROGETTO like '%privacy%'
   or CUP_DESCR_NATURA like '%privacy%'
   or CUP_DESCR_SETTORE like '%privacy%'
   or CUP_DESCR_SOTTOSETTORE like '%privacy%'
   or CUP_DESCR_CATEGORIA like '%privacy%'
   or OC_TITOLO_PROGETTO like '%autenticazione%'
   or OC_SINTESI_PROGETTO like '%autenticazione%'
   or CUP_DESCR_NATURA like '%autenticazione%'
   or CUP_DESCR_SETTORE like '%autenticazione%'
   or CUP_DESCR_SOTTOSETTORE like '%autenticazione%'
   or CUP_DESCR_CATEGORIA like '%autenticazione%'
   or OC_TITOLO_PROGETTO like '%VPN%'
   or OC_SINTESI_PROGETTO like '%VPN%'
   or CUP_DESCR_NATURA like '%VPN%'
   or CUP_DESCR_SETTORE like '%VPN%'
   or CUP_DESCR_SOTTOSETTORE like '%VPN%'
   or CUP_DESCR_CATEGORIA like '%VPN%';
   --big data
   or OC_TITOLO_PROGETTO like '%big data%'
   or OC_SINTESI_PROGETTO like '%big data%'
   or CUP_DESCR_NATURA like '%big data%'
   or CUP_DESCR_TIPOLOGIA like '%big data%'
   or CUP_DESCR_SETTORE like '%big data%'
   or CUP_DESCR_SOTTOSETTORE like '%big data%'
   or CUP_DESCR_CATEGORIA like '%big data%'
   or OC_TITOLO_PROGETTO like '%analytics%'
   or OC_SINTESI_PROGETTO like '%analytics%'
   or CUP_DESCR_NATURA like '%analytics%'
   or CUP_DESCR_TIPOLOGIA like '%analytics%'
   or CUP_DESCR_SETTORE like '%analytics%'
   or CUP_DESCR_SOTTOSETTORE like '%analytics%'
   or CUP_DESCR_CATEGORIA like '%analytics%'
   or OC_TITOLO_PROGETTO like '%analisi dei dati%'
   or OC_SINTESI_PROGETTO like '%analisi dei dati%'
   or CUP_DESCR_NATURA like '%analisi dei dati%'
   or CUP_DESCR_TIPOLOGIA like '%analisi dei dati%'
   or CUP_DESCR_SETTORE like '%analisi dei dati%'
   or CUP_DESCR_SOTTOSETTORE like '%analisi dei dati%'
   or CUP_DESCR_CATEGORIA like '%analisi dei dati%'
   or OC_TITOLO_PROGETTO like '%data mining%'
   or OC_SINTESI_PROGETTO like '%data mining%'
   or CUP_DESCR_NATURA like '%data mining%'
   or CUP_DESCR_TIPOLOGIA like '%data mining%'
   or CUP_DESCR_SETTORE like '%data mining%'
   or CUP_DESCR_SOTTOSETTORE like '%data mining%'
   or CUP_DESCR_CATEGORIA like '%data mining%'
   or OC_TITOLO_PROGETTO like '%machine learning%'
   or OC_SINTESI_PROGETTO like '%machine learning%'
   or CUP_DESCR_NATURA like '%machine learning%'
   or CUP_DESCR_TIPOLOGIA like '%machine learning%'
   or CUP_DESCR_SETTORE like '%machine learning%'
   or CUP_DESCR_SOTTOSETTORE like '%machine learning%'
   or CUP_DESCR_CATEGORIA like '%machine learning%';
